import type { LucideProps } from 'lucide-react';
import {
  BarChart3,
  CheckCircle,
  ChevronRight,
  Clock,
  Folder,
  FolderOpen,
  GitBranch,
  GitCommit,
  GitMerge,
  LayoutGrid,
  Menu,
  MoreHorizontal,
  Network,
  Plus,
  Search,
  Settings,
  Star,
  Trash2,
  Undo2,
  X,
  Bell,
  Calendar,
  ChevronLeft,
  Download,
  Edit3,
  Filter,
  Home,
  Info,
  Moon,
  Sun,
  Upload,
  AlertCircle,
  AlertTriangle,
  Check,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from 'lucide-react';

export enum AppIconName {
  repository = 'repository',
  repositoryOpen = 'repositoryOpen',
  heatmap = 'heatmap',
  graph = 'graph',
  settings = 'settings',
  add = 'add',
  edit = 'edit',
  delete = 'delete',
  search = 'search',
  back = 'back',
  close = 'close',
  more = 'more',
  chevronRight = 'chevronRight',
  checkCircle = 'checkCircle',
  undo = 'undo',
  calendar = 'calendar',
  fork = 'fork',
  star = 'star',
  success = 'success',
  error = 'error',
  warning = 'warning',
  info = 'info',
  darkMode = 'darkMode',
  upload = 'upload',
  download = 'download',
  deleteSweep = 'deleteSweep',
  notifications = 'notifications',
  timer = 'timer',
  zoomIn = 'zoomIn',
  zoomOut = 'zoomOut',
  reset = 'reset',
  gitBranch = 'gitBranch',
  gitCommit = 'gitCommit',
  gitMerge = 'gitMerge',
  home = 'home',
  menu = 'menu',
  layoutGrid = 'layoutGrid',
  filter = 'filter',
  moon = 'moon',
  sun = 'sun',
  check = 'check',
  alertCircle = 'alertCircle',
  alertTriangle = 'alertTriangle',
}

const iconMap: Record<AppIconName, LucideIcon> = {
  [AppIconName.repository]: Folder,
  [AppIconName.repositoryOpen]: FolderOpen,
  [AppIconName.heatmap]: BarChart3,
  [AppIconName.graph]: Network,
  [AppIconName.settings]: Settings,
  [AppIconName.add]: Plus,
  [AppIconName.edit]: Edit3,
  [AppIconName.delete]: Trash2,
  [AppIconName.search]: Search,
  [AppIconName.back]: ChevronLeft,
  [AppIconName.close]: X,
  [AppIconName.more]: MoreHorizontal,
  [AppIconName.chevronRight]: ChevronRight,
  [AppIconName.checkCircle]: CheckCircle,
  [AppIconName.undo]: Undo2,
  [AppIconName.calendar]: Calendar,
  [AppIconName.fork]: GitBranch,
  [AppIconName.star]: Star,
  [AppIconName.success]: CheckCircle,
  [AppIconName.error]: AlertCircle,
  [AppIconName.warning]: AlertTriangle,
  [AppIconName.info]: Info,
  [AppIconName.darkMode]: Moon,
  [AppIconName.upload]: Upload,
  [AppIconName.download]: Download,
  [AppIconName.deleteSweep]: Trash2,
  [AppIconName.notifications]: Bell,
  [AppIconName.timer]: Clock,
  [AppIconName.zoomIn]: ZoomIn,
  [AppIconName.zoomOut]: ZoomOut,
  [AppIconName.reset]: RotateCcw,
  [AppIconName.gitBranch]: GitBranch,
  [AppIconName.gitCommit]: GitCommit,
  [AppIconName.gitMerge]: GitMerge,
  [AppIconName.home]: Home,
  [AppIconName.menu]: Menu,
  [AppIconName.layoutGrid]: LayoutGrid,
  [AppIconName.filter]: Filter,
  [AppIconName.moon]: Moon,
  [AppIconName.sun]: Sun,
  [AppIconName.check]: Check,
  [AppIconName.alertCircle]: AlertCircle,
  [AppIconName.alertTriangle]: AlertTriangle,
};

export interface AppIconProps extends Omit<LucideProps, 'ref'> {
  name: AppIconName;
}

export function AppIcon({ name, ...props }: AppIconProps): JSX.Element | null {
  const Icon = iconMap[name];
  if (!Icon) return null;
  return <Icon {...props} />;
}

export type { LucideIcon };
