import type { Config } from 'tailwindcss';
import tailwindcssAnimate from 'tailwindcss-animate';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    screens: {
      mobile: '0px',
      tablet: '768px',
      laptop: '1024px',
      desktop: '1280px',
      'desktop-xl': '1440px',
    },
    extend: {
      colors: {
        canvas: 'var(--color-canvas)',
        'surface-1': 'var(--color-surface-1)',
        'surface-2': 'var(--color-surface-2)',
        'surface-3': 'var(--color-surface-3)',
        'surface-4': 'var(--color-surface-4)',
        hairline: 'var(--color-hairline)',
        'hairline-strong': 'var(--color-hairline-strong)',
        'hairline-tertiary': 'var(--color-hairline-tertiary)',
        ink: 'var(--color-ink)',
        'ink-muted': 'var(--color-ink-muted)',
        'ink-subtle': 'var(--color-ink-subtle)',
        'ink-tertiary': 'var(--color-ink-tertiary)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-focus': 'var(--color-primary-focus)',
        'primary-dark': 'var(--color-primary-dark)',
        'on-primary': 'var(--color-on-primary)',
        success: 'var(--color-success)',
        'success-light': 'var(--color-success-light)',
        warning: 'var(--color-warning)',
        'warning-light': 'var(--color-warning-light)',
        error: 'var(--color-error)',
        'error-light': 'var(--color-error-light)',
        info: 'var(--color-info)',
        overlay: 'var(--color-overlay)',
        'inverse-canvas': 'var(--color-inverse-canvas)',
        'inverse-ink': 'var(--color-inverse-ink)',
        'priority-high': 'var(--color-priority-high)',
        'priority-medium': 'var(--color-priority-medium)',
        'priority-low': 'var(--color-priority-low)',
        'status-todo': 'var(--color-status-todo)',
        'status-in-progress': 'var(--color-status-in-progress)',
        'status-done': 'var(--color-status-done)',
        'status-cancelled': 'var(--color-status-cancelled)',
        'heatmap-empty': 'var(--color-heatmap-empty)',
        'heatmap-1': 'var(--color-heatmap-1)',
        'heatmap-2': 'var(--color-heatmap-2)',
        'heatmap-3': 'var(--color-heatmap-3)',
        'heatmap-4': 'var(--color-heatmap-4)',
      },
      fontFamily: {
        sans: [
          'Segoe UI',
          'Microsoft YaHei UI',
          'PingFang SC',
          'Noto Sans CJK SC',
          'Noto Sans SC',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'JetBrains Mono',
          'Cascadia Mono',
          'SF Mono',
          'Menlo',
          'Consolas',
          'Microsoft YaHei UI',
          'Noto Sans CJK SC',
          'monospace',
        ],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.05', letterSpacing: '-2.0px' }],
        'display-lg': ['40px', { lineHeight: '1.10', letterSpacing: '-1.5px' }],
        'display-md': ['32px', { lineHeight: '1.15', letterSpacing: '-1.0px' }],
        headline: ['24px', { lineHeight: '1.20', letterSpacing: '-0.6px' }],
        subhead: ['20px', { lineHeight: '1.40', letterSpacing: '-0.2px' }],
        'card-title': ['17px', { lineHeight: '1.25', letterSpacing: '-0.4px' }],
        'body-lg': ['17px', { lineHeight: '1.50', letterSpacing: '-0.1px' }],
        body: ['15px', { lineHeight: '1.50', letterSpacing: '-0.05px' }],
        'body-sm': ['13px', { lineHeight: '1.50', letterSpacing: '0' }],
        button: ['14px', { lineHeight: '1.20', letterSpacing: '0' }],
        caption: ['11px', { lineHeight: '1.40', letterSpacing: '0' }],
        eyebrow: ['12px', { lineHeight: '1.30', letterSpacing: '0.4px' }],
        'mono-sm': ['11px', { lineHeight: '1.40', letterSpacing: '0' }],
      },
      spacing: {
        micro: '2px',
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '24px',
        pill: '999px',
        full: '999px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.05)',
        md: '0 2px 6px rgba(0,0,0,0.1)',
        lg: '0 4px 12px rgba(0,0,0,0.15)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '250ms',
        slow: '350ms',
      },
      transitionTimingFunction: {
        'out-quart': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
